language: bash

dist: xenial

script:
    - bash $HOME/dependancies/update_installation.sh
    - bash $HOME/dependancies/dependencies_installation.sh
    - bash $HOME/dependancies/apache2_installation.sh
    - bash $HOME/dependancies/mysql_installation.sh
    - bash $HOME/dependancies/php7.3_installation.sh
    - bash $HOME/dependancies/xdebug_installation.sh
    - bash $HOME/dependancies/composer_installation.sh
    - bash $HOME/dependancies/php-cs-fixer_installation.sh
    - bash $HOME/dependancies/php-code-sniffer_installation.sh
    - bash $HOME/dependancies/php-mess-detector_installation.sh
    - bash $HOME/dependancies/copy-paste-detector_installation.sh
    - bash $HOME/dependancies/samba_installation.sh
    - bash $HOME/dependancies/blackFire_installation.sh
    - bash $HOME/dependancies/zsh_installation.sh
    - bash $HOME/dependancies/cleaning_installation.sh
    - bash $HOME/install.sh n
